### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Metaxal** [mosceo/tetris#2]
The info.rkt needs to be fixed
https://pkg-build.racket-lang.org/server/built/deps/tetris.txt
Just making a note of this. Happy to fix it myself (when I find the time and I'm on my personal computer)

**Comment by mosceo** [comment]
Hello.

I tried to fix failing unit tests issue. The problem is in the size of the board. For playing a **10x22** board is used, but the tests are written for a **5x6** board.

In `tetris.rkt` there is this block of code:

```racket
;;=======================================
;; Global constants
;;=======================================

;; FOR UNIT TESTS
;(define W 5)
;(define H 6)

;; FOR PLAYING
(define W 10)         ;; board width  (# of blocks)
(define H 22)         ;; board height (# of blocks)
```

I don't know how to make that when `unittest.rkt` is run the program use different constants. It would solve the issue. I have not programmed in Racket for a couple of years. I would be glad if you helped me.
